coverage:
  status:
    project:
      default:
        target: 80%    # the required coverage value
        threshold: 1%  # the leniency in hitting the target
    patch:
      default:
        target: 80%

ignore:
  - "**/*.g.dart"    # generated files
  - "**/*.freezed.dart"
  - "lib/generated/"
  - "lib/l10n/" 