name: CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    tags:
      - 'v*'
  workflow_dispatch:

# 设置并发控制，确保同一分支不会重复运行
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION: '3.24.1'
  JAVA_VERSION: '17'

jobs:
  # 复用的 setup 步骤
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.value }}
    steps:
      - id: cache-key
        run: echo "value=${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}" >> $GITHUB_OUTPUT

  analyze-and-test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 缓存 Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      # 缓存 pub 依赖
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.PUB_CACHE }}
            .dart_tool
          key: ${{ needs.setup.outputs.cache-key }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      
      - name: Install Dependencies
        run: flutter pub get
        
      - name: Verify Formatting
        run: dart format --output=none --set-exit-if-changed .
        
      - name: Analyze Project Source
        run: flutter analyze
        
      - name: Run Tests
        run: flutter test --coverage
        
      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
          fail_ci_if_error: true

  # PR 时的构建测试
  test-build:
    if: github.event_name == 'pull_request'
    needs: [setup, analyze-and-test]
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: android
            build-command: flutter build apk --debug # 使用 debug 模式加快构建
          - os: macos-latest
            target: macos
            build-command: flutter build macos --debug # 使用 debug 模式加快构建
          - os: macos-latest
            target: ios
            build-command: flutter build ios --debug --no-codesign # 使用 debug 模式加快构建
      fail-fast: true # 开启快速失败，节省时间
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # 减少克隆深度
      
      - if: matrix.target == 'android'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.PUB_CACHE }}
            .dart_tool
            ${{ matrix.target == 'ios' && 'ios/Pods' || '' }}
            build
          key: ${{ needs.setup.outputs.cache-key }}-${{ matrix.target }}-build
          restore-keys: |
            ${{ runner.os }}-flutter-${{ matrix.target }}-build-
            ${{ runner.os }}-flutter-${{ matrix.target }}-
      
      - name: Install Dependencies
        run: |
          flutter pub get --no-precompile # 跳过预编译
          if [ "${{ matrix.target }}" = "ios" ]; then
            cd ios && pod install --deployment && cd .. # 使用更快的 pod install
          fi
      
      - name: Test Build ${{ matrix.target }}
        run: ${{ matrix.build-command }}
  # Release 构建
  build:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [setup, analyze-and-test]
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: android
            build-command: flutter build apk --release
            artifact-path: build/app/outputs/flutter-apk/twoFactorAuth.apk
            artifact-name: android-release
          - os: macos-latest
            target: macos
            build-command: |
              flutter build macos --release
              brew install create-dmg
              create-dmg \
                --volname "TwoFactorAuth" \
                --window-pos 200 120 \
                --window-size 800 400 \
                --icon-size 100 \
                --icon "TwoFactorAuth.app" 200 190 \
                --hide-extension "TwoFactorAuth.app" \
                --app-drop-link 600 185 \
                "TwoFactorAuth.dmg" \
                "build/macos/Build/Products/Release/TwoFactorAuth.app"
            artifact-path: TwoFactorAuth.dmg
            artifact-name: macos-release
          - os: macos-latest
            target: ios
            build-command: flutter build ios --release --no-codesign
            artifact-path: build/ios/iphoneos/twoFactorAuth.ipa
            artifact-name: ios-release
      fail-fast: false
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - if: matrix.target == 'android'
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.PUB_CACHE }}
            .dart_tool
            ${{ matrix.target == 'ios' && 'ios/Pods' || '' }}
          key: ${{ needs.setup.outputs.cache-key }}-${{ matrix.target }}
          restore-keys: |
            ${{ runner.os }}-flutter-${{ matrix.target }}-
      
      - name: Install Dependencies
        run: |
          flutter pub get
          if [ "${{ matrix.target }}" = "ios" ]; then
            cd ios && pod install && cd ..
          fi
      
      - name: Build ${{ matrix.target }}
        run: ${{ matrix.build-command }}
      
      - if: matrix.target == 'ios'
        name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r twoFactorAuth.ipa Payload
        
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: ${{ matrix.artifact-path }}
          retention-days: 5

  # 只在打tag时创建release
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      # 添加调试步骤
      - name: List Artifacts
        run: |
          echo "Artifacts directory contents:"
          ls -R artifacts/
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/android-release/twoFactorAuth.apk
            artifacts/macos-release/twoFactorAuth.dmg
            artifacts/ios-release/twoFactorAuth.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}