name: Release

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: ''
      is_release:
        required: true
        type: boolean
        description: "Whether this is a release build"

jobs:
  release:
    if: inputs.is_release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            build_target: apk
          - os: macos-latest
            build_target: ios,macos
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get

      # Android构建
      - name: Build Android
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --release

      # macOS构建
      - name: Build macOS
        if: matrix.os == 'macos-latest'
        run: |
          flutter config --enable-macos-desktop
          flutter build macos --release
          cd build/macos/Build/Products/Release
          zip -r ../../../../../macos.zip *.app

      # iOS构建
      - name: Build iOS
        if: matrix.os == 'macos-latest'
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          zip -r ../../../ios.zip .

      # 上传构建产物
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: |
            *.zip
            build/app/outputs/flutter-apk/*.apk

      # 下载所有构建产物并创建Release
      - name: Download all artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Create Release
        if: matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/*.zip
            artifacts/**/*.apk
          draft: false
          prerelease: false
          generate_release_notes: true