# 可重用的步骤定义
name: Reusable Steps

on:
  workflow_call:
    inputs:
      os:
        description: "Runner OS"
        required: false
        type: string
        default: 'ubuntu-latest'
      flutter_version:
        description: "Flutter version"
        required: false
        type: string
        default: '3.24.1'
    outputs:
      flutter-path:
        description: "Flutter installation path"
        value: ${{ jobs.flutter-setup.outputs.flutter-path }}

jobs:
  flutter-setup:
    runs-on: ${{ inputs.os }}
    outputs:
      flutter-path: ${{ steps.flutter-setup.outputs.FLUTTER_ROOT }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Flutter
        id: flutter-setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter_version }}
          channel: 'stable'
          cache: true
      
      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-
      
      - name: Install dependencies
        run: flutter pub get