name: Verify Builds

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
        default: ''

jobs:
  verify-builds:
    name: Verify ${{ matrix.build_target }} build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            build_target: android
          - os: macos-latest
            build_target: ios,macos
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get

      # Android构建验证
      - name: Verify Android build
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --debug
        
      # iOS构建验证
      - name: Verify iOS build
        if: matrix.os == 'macos-latest'
        run: flutter build ios --debug --no-codesign
        
      # macOS构建验证
      - name: Verify macOS build
        if: matrix.os == 'macos-latest'
        run: |
          flutter config --enable-macos-desktop
          flutter build macos --debug