name: Verify Builds

on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed
    branches:
      - master

jobs:
  verify-builds:
    name: Verify ${{ matrix.build_target }} build
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.workflow_run.event == 'push'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            build_target: android
          - os: macos-latest
            build_target: ios,macos
    runs-on: ${{ matrix.os }}
    steps:
      - name: Debug workflow_run event
        run: |
          echo "Workflow name: ${{ github.event.workflow_run.name }}"
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Workflow event: ${{ github.event.workflow_run.event }}"
          echo "Workflow id: ${{ github.event.workflow_run.id }}"
          
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'
          channel: 'stable'
          cache: true
      
      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.PUB_CACHE }}
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-pub-
      
      - name: Install dependencies
        run: flutter pub get

      # Android构建验证
      - name: Verify Android build
        if: matrix.os == 'ubuntu-latest'
        run: flutter build apk --debug
        
      # iOS构建验证
      - name: Verify iOS build
        if: matrix.os == 'macos-latest'
        run: flutter build ios --debug --no-codesign
        
      # macOS构建验证
      - name: Verify macOS build
        if: matrix.os == 'macos-latest'
        run: |
          flutter config --enable-macos-desktop
          flutter build macos --debug